// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOP.Models;

#nullable disable

namespace OOP.Migrations
{
    [DbContext(typeof(TaskManagementDBContext))]
    [Migration("20250522052614_v5")]
    partial class v5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("NotiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("NotiID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OOP.Models.Meeting", b =>
                {
                    b.Property<int>("taskID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TaskName");

                    b.HasKey("taskID");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("ProjectID");

                    b.ToTable("Meetings", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("OOP.Models.MeetingMemberManagement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("MeetingID");

                    b.HasIndex("UserID");

                    b.ToTable("MeetingMemberManagement");
                });

            modelBuilder.Entity("OOP.Models.Milestone", b =>
                {
                    b.Property<int>("taskID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TaskName");

                    b.HasKey("taskID");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("ProjectID");

                    b.ToTable("Milestones", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("OOP.Models.Project", b =>
                {
                    b.Property<int>("projectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("projectDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Project Name");

                    b.HasKey("projectID");

                    b.HasIndex("AdminID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("OOP.Models.Task", b =>
                {
                    b.Property<int>("taskID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TaskName");

                    b.HasKey("taskID");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("ProjectID");

                    b.ToTable("Tasks", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("OOP.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MeetingtaskID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("User Name");

                    b.HasKey("ID");

                    b.HasIndex("MeetingtaskID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("OOP.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OOP.Models.Meeting", b =>
                {
                    b.HasOne("OOP.Models.User", "UserAssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("UserAssignedTo");
                });

            modelBuilder.Entity("OOP.Models.MeetingMemberManagement", b =>
                {
                    b.HasOne("OOP.Models.Meeting", "Meeting")
                        .WithMany("MeetingUsers")
                        .HasForeignKey("MeetingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP.Models.User", "User")
                        .WithMany("MeetingUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OOP.Models.Milestone", b =>
                {
                    b.HasOne("OOP.Models.User", "UserAssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("UserAssignedTo");
                });

            modelBuilder.Entity("OOP.Models.Project", b =>
                {
                    b.HasOne("OOP.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("OOP.Models.Task", b =>
                {
                    b.HasOne("OOP.Models.User", "UserAssignedTo")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("UserAssignedTo");
                });

            modelBuilder.Entity("OOP.Models.User", b =>
                {
                    b.HasOne("OOP.Models.Meeting", null)
                        .WithMany("Participants")
                        .HasForeignKey("MeetingtaskID");
                });

            modelBuilder.Entity("OOP.Models.Meeting", b =>
                {
                    b.Navigation("MeetingUsers");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("OOP.Models.User", b =>
                {
                    b.Navigation("MeetingUsers");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
